### ISSUE TITLE
Waferscreen misidentifying which band is screened

### ISSUE THREAD

**Issue by braddober** [chw3k5/WaferScreen#8]
Hi Caleb,

We screened a package with B0,B1, and B12,B13. The screener code is misidentifying these chips at B1 and B11.
Is this a problem due to overlapping bands, or is it something wrong with the code?
[ScatterHist_Band01_Wafer018_curated.pdf](https://github.com/chw3k5/WaferScreen/files/6896070/ScatterHist_Band01_Wafer018_curated.pdf)
[ScatterHist_Band11_Wafer018_curated.pdf](https://github.com/chw3k5/WaferScreen/files/6896071/ScatterHist_Band11_Wafer018_curated.pdf)

Let me know if you have the capacity to take a look at this.

Sincerely,

Brad Dober

**Comment by chw3k5** [comment]
Not a bug. The band finding algorithm looks for a **large spacing between resonators** to identify the band edges. It did not find the requested spacing and continued as if the resonators were all part of the same band. It is quite the compliment that you thought I had solved this problem for adjacent (and collided) bands. Since the upper bands (bands 9-14) are often had the majority of resonators in the next neighboring band, the aloratim is expecting **all the chips on an RF chain to be all even or all odd bands**. Once the frequency corrections are made and verified for subsequent wafers, one may consider removing this requirement. This also bring me to an existential question I never answered, if most of a Band12 chip's resonators are in Band13, isn't that really a Band13 chip.

In case you want to modify this (simple) algorithm, it can be found in the file:
[waferscreen/analyze/res_pipeline.py](https://github.com/chw3k5/WaferScreen/blob/master/waferscreen/analyze/res_pipeline.py)
in the class ResPipe with the method scan_to_band() at line 450. Note the I parameterized the spacing threshold, i.e. it is controlled by the variable connected_group_threshold_ghz. In python we write:
`waferscreen.analyze.res_pipeline.ResPipe.scan_to_band(connected_group_threshold_ghz=0.07)`

Band identification happens as the resonators are initially scanned, this information is the seed for the flux ramp survey. You could have identified issue after that processing on the scan was completed, before the flux ramp survey was conducted. Band determination is so important it gets its own plot, band_report.pdf. I have include an example of the band_report.pdf plot for wafer 14 as well as a screenshot to remind you of the file hierarchy in which to find this type of file. 

[band_report.pdf](https://github.com/chw3k5/WaferScreen/files/6897159/band_report.pdf)
![image](https://user-images.githubusercontent.com/8564941/127414427-f0771d9b-2fb5-4041-9ad4-e0c6d4687ad4.png)

**Comment by braddober** [comment]
Hi Caleb,

Thanks for the detailed response. It seems to be what I figured, that band identification requires chips to not be adjacent.
Thanks for pointing out the location in the code where this takes place. That's very helpful.

Sincerely,

Brad
